global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rag-app'
    static_configs:
      - targets: ['rag-app:8001']

  - job_name: 'vllm-server'
    static_configs:
      - targets: ['vllm-server:8000']

